# Generated by Django 5.0.6 on 2024-12-24 09:12

import work.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contract_deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[work.models.validate_mobile_number])),
                ('contract_deal', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('contract_type', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_site', models.CharField(max_length=100, validators=[work.models.validate_only_letters])),
                ('location', models.CharField(max_length=100, validators=[work.models.validate_only_letters])),
                ('name_of_the_employee', models.CharField(max_length=100, validators=[work.models.validate_only_letters])),
                ('phone_number', models.CharField(max_length=10, validators=[work.models.validate_mobile_number])),
                ('to_day_expensives', models.CharField(max_length=10, validators=[work.models.validate_expenses])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
